### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dawidd6** [dawidd6/minifetch#1]
- [x] count installed packages
- [x] volume level
- [x] mpc current song + vol maybe
- [x] ~~cpu temp and usage(load)~~
- [ ] more distros support
